name = "wampin-13-month-calendar"
compatibility_date = "2024-01-01"

# Build configuration
[build]
command = "npm run build"
directory = "dist"

# Environment variables
[vars]
# Add non-sensitive variables here

# For local development, create a .dev.vars file with:
# GOOGLE_CLIENT_ID=your-google-client-id
# GOOGLE_CLIENT_SECRET=your-google-client-secret

# Pages Functions configuration
[[routes]]
pattern = "/api/*"
zone_name = ""